package com.jriddler.attr;

import com.jriddler.TestDbInstance;
import com.jriddler.attrs.AttributeDefinition;
import com.jriddler.attrs.Attributes;
import org.hamcrest.CoreMatchers;
import org.junit.Assert;
import org.junit.Test;

import java.util.List;

/**
 * Test {@link Attributes}.
 */
@SuppressWarnings("MagicNumber")
public final class AttributesTestCase extends TestDbInstance {

    /**
     * Test that actual table attrs were fetched.
     */
    @Test
    public void testAttributes() {
        final List<AttributeDefinition> attributes =
                new Attributes(
                        "users",
                        this.jdbcTemplate
                );
        Assert.assertThat(
                attributes.get(0).name(),
                CoreMatchers.is("id")
        );
        Assert.assertThat(
                attributes.get(1).name(),
                CoreMatchers.is("name")
        );
        Assert.assertThat(
                attributes.get(2).name(),
                CoreMatchers.is("surname")
        );
        Assert.assertThat(
                attributes.get(3).name(),
                CoreMatchers.is("age")
        );
        Assert.assertThat(
                attributes.get(4).name(),
                CoreMatchers.is("active")
        );
        Assert.assertThat(
                attributes.get(5).name(),
                CoreMatchers.is("birthday")
        );
    }

    /**
     * Test that autogenerated keys are skipped.
     * Managers table has 4 attrs
     * two of them are serials
     */
    @Test
    public void testAutoGeneratedAttrs() {
        final List<AttributeDefinition> attributes =
                new Attributes(
                        "managers",
                        this.jdbcTemplate
                );
        Assert.assertThat(
                attributes.size(),
                CoreMatchers.is(2)
        );
        Assert.assertThat(
                attributes.get(0).name(),
                CoreMatchers.is("id3")
        );
        Assert.assertThat(
                attributes.get(1).name(),
                CoreMatchers.is("id4")
        );
    }

}
